In [1]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import groq

In [2]:
df_items=pd.read_json("./../data/meta_CDs_and_Vinyl_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [3]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Digital Music,Queen II[LP],4.7,1835,[],[Queen II is the second studio album from the ...,29.33,[{'thumb': 'https://m.media-amazon.com/images/...,[],Queen Format: Vinyl,"[CDs & Vinyl, Rock]","{'Language': 'English', 'Product Dimensions': ...",B0BDFW4VRB,NaN
1,Digital Music,The Elephants of Mars Limited Orange,4.7,125,[],"[It moves, it swings, it rocks!Satriani and hi...",26.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],Joe Satriani Format: Vinyl,"[CDs & Vinyl, Rock]",{'Product Dimensions': '12 x 12.3 x 0.4 inches...,B09Q98326Z,NaN
2,Digital Music,The Love Invention Heavyweight Black,4.5,158,[],[Alison Goldfrapp has set a towering bar for B...,20.49,[{'thumb': 'https://m.media-amazon.com/images/...,[],Alison Goldfrapp (Artist) Format: Vinyl,"[CDs & Vinyl, Dance & Electronic, Electronica]","{'Language': 'English', 'Product Dimensions': ...",B0BYHFG53W,NaN
3,Digital Music,Now That's What I Call A Love Song / Various,4.5,120,[],[NOW Music is proud to present 80 of the great...,25.68,[{'thumb': 'https://m.media-amazon.com/images/...,[],Various Artists (Artist) Format: Audio CD,"[CDs & Vinyl, Rock]",{'Package Dimensions': '5.51 x 4.92 x 0.51 inc...,B0BS1SHT91,NaN
4,Digital Music,SZNZ: Summer,4.4,120,[],"[SZNZ: Summer, the second part in Weezer's fou...",8.79,[{'thumb': 'https://m.media-amazon.com/images/...,[],Weezer Format: Audio CD,"[CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi]","{'Language': 'English', 'Product Dimensions': ...",B0B2ZRV4FD,NaN

In [4]:
#swap features and description coloumns
df_items["features"], df_items["description"] = df_items["description"], df_items["features"]

In [5]:
list(df_items["features"].items())[0]

(0,
 ['Queen II is the second studio album from the iconic British rock band. Originally released in 1974, it reached #5 on the U.K. albums chart. This reissue is pressed on 180-gram vinyl and sourced from the original master tapes.'])

In [6]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together
0,Digital Music,Queen II[LP],4.7,1835,[Queen II is the second studio album from the ...,[],29.33,[{'thumb': 'https://m.media-amazon.com/images/...,[],Queen Format: Vinyl,"[CDs & Vinyl, Rock]","{'Language': 'English', 'Product Dimensions': ...",B0BDFW4VRB,NaN
1,Digital Music,The Elephants of Mars Limited Orange,4.7,125,"[It moves, it swings, it rocks!Satriani and hi...",[],26.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],Joe Satriani Format: Vinyl,"[CDs & Vinyl, Rock]",{'Product Dimensions': '12 x 12.3 x 0.4 inches...,B09Q98326Z,NaN
2,Digital Music,The Love Invention Heavyweight Black,4.5,158,[Alison Goldfrapp has set a towering bar for B...,[],20.49,[{'thumb': 'https://m.media-amazon.com/images/...,[],Alison Goldfrapp (Artist) Format: Vinyl,"[CDs & Vinyl, Dance & Electronic, Electronica]","{'Language': 'English', 'Product Dimensions': ...",B0BYHFG53W,NaN
3,Digital Music,Now That's What I Call A Love Song / Various,4.5,120,[NOW Music is proud to present 80 of the great...,[],25.68,[{'thumb': 'https://m.media-amazon.com/images/...,[],Various Artists (Artist) Format: Audio CD,"[CDs & Vinyl, Rock]",{'Package Dimensions': '5.51 x 4.92 x 0.51 inc...,B0BS1SHT91,NaN
4,Digital Music,SZNZ: Summer,4.4,120,"[SZNZ: Summer, the second part in Weezer's fou...",[],8.79,[{'thumb': 'https://m.media-amazon.com/images/...,[],Weezer Format: Audio CD,"[CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi]","{'Language': 'English', 'Product Dimensions': ...",B0B2ZRV4FD,NaN

In [7]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/41wmg-DUsDL._SS40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41wmg-DUsDL.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/61VO5mwSWcL._SL1500_.jpg'}])

### Preprocess Title and features

In [8]:
def preprocess_features(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [9]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [10]:
df_items["description"] = df_items.apply(preprocess_features, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [11]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,image
0,Digital Music,Queen II[LP],4.7,1835,[Queen II is the second studio album from the ...,Queen II[LP] Queen II is the second studio alb...,29.33,[{'thumb': 'https://m.media-amazon.com/images/...,[],Queen Format: Vinyl,"[CDs & Vinyl, Rock]","{'Language': 'English', 'Product Dimensions': ...",B0BDFW4VRB,NaN,https://m.media-amazon.com/images/I/41wmg-DUsD...
1,Digital Music,The Elephants of Mars Limited Orange,4.7,125,"[It moves, it swings, it rocks!Satriani and hi...","The Elephants of Mars Limited Orange It moves,...",26.98,[{'thumb': 'https://m.media-amazon.com/images/...,[],Joe Satriani Format: Vinyl,"[CDs & Vinyl, Rock]",{'Product Dimensions': '12 x 12.3 x 0.4 inches...,B09Q98326Z,NaN,https://m.media-amazon.com/images/I/31uqhdHGwB...
2,Digital Music,The Love Invention Heavyweight Black,4.5,158,[Alison Goldfrapp has set a towering bar for B...,The Love Invention Heavyweight Black Alison Go...,20.49,[{'thumb': 'https://m.media-amazon.com/images/...,[],Alison Goldfrapp (Artist) Format: Vinyl,"[CDs & Vinyl, Dance & Electronic, Electronica]","{'Language': 'English', 'Product Dimensions': ...",B0BYHFG53W,NaN,https://m.media-amazon.com/images/I/41Y1Uqko5C...
3,Digital Music,Now That's What I Call A Love Song / Various,4.5,120,[NOW Music is proud to present 80 of the great...,Now That's What I Call A Love Song / Various N...,25.68,[{'thumb': 'https://m.media-amazon.com/images/...,[],Various Artists (Artist) Format: Audio CD,"[CDs & Vinyl, Rock]",{'Package Dimensions': '5.51 x 4.92 x 0.51 inc...,B0BS1SHT91,NaN,https://m.media-amazon.com/images/I/51QqhSYl+D...
4,Digital Music,SZNZ: Summer,4.4,120,"[SZNZ: Summer, the second part in Weezer's fou...","SZNZ: Summer SZNZ: Summer, the second part in ...",8.79,[{'thumb': 'https://m.media-amazon.com/images/...,[],Weezer Format: Audio CD,"[CDs & Vinyl, Indie & Alternative, Indie & Lo-Fi]","{'Language': 'English', 'Product Dimensions': ...",B0B2ZRV4FD,NaN,https://m.media-amazon.com/images/I/51Fv6K5rZ8...

#### Sample 50 items from dataset (for quick devlopment)

In [12]:
df_sample=df_items.sample(50, random_state=42)

In [13]:
len(df_sample)

50

In [14]:
data_to_embed=df_sample[["description", "image","rating_number","price","average_rating","parent_asin"]].to_dict(orient="records")

In [15]:
data_to_embed

[{'description': "I Am The Moon: IV. Farewell The fifth studio project from the Tedeschi Trucks band is the most ambitious and, at the same time, intimate record that America's best rock n' roll big band has ever made: a genuinely epic undertaking in four episodes and 24 songs inspired by classical literature but emotionally driven by the immediate drama, isolation and mourning of the pandemic era. CD Softpak.",
  'image': 'https://m.media-amazon.com/images/I/315JEh2Xh9L.jpg',
  'rating_number': 309,
  'price': 10.98,
  'average_rating': 4.7,
  'parent_asin': 'B09XVCWQGL'},
 {'description': 'When Christmas Comes Around... GRAMMY-winning global superstarKellyClarksonhas announcedWhen Christmas Comes Around…on vinyl, her ninth studio album arrived viaAtlanticRecordsin 2021. Led by the fabulously bold lead single “Christmas Isn’t Canceled (Just You),” the album explores a wide range of holiday emotions and experiences anchored by Clarkson’s incomparable vocal prowess. From the show-stopping duet “Santa, Can’t You Hear Me” featuringAriana Grandeto the hauntingly beautiful ballad “Merry Christmas (To The One I Used To Know),”When Christmas Comes Around…explores a wide range of holiday emotions and experiences anchored by Clarkson’s incomparable vocal prowess. The album also features cheerful standout “Glow” featuringChrisStapletonand the fabulously bold lead single “Christmas Isn’t Canceled (Just You),” the latter of which was deemed“a sassy bop”byEntertainment Weeklyand“infused with empowerment”byUSAToday.“’When Christmas Comes Around…’ captures how different the holidays can be for all of us during the varying stages of our lives, and I hope everyone can find something on the record they relate to. Hopefully the happier songs, but if not, hey… you’re not alone!” –KELLYCLARKSON',
  'image': 'https://m.media-amazon.com/images/I/41jGW11iSyL.jpg',
  'rating_number': 2434,
  'price': 20.94,
  'average_rating': 4.8,
  'parent_asin': 'B0B832LSNC'},
 {'description': "Andrew Bird Inside Problems (Indie Exclusive, Col Exclusive Apple Red Vinyl LP edition of Inside Problems.  Side A 1. Underlands 2. Lone Didion 3. Fixed Positions 4. Inside Problems 5. The Night Before Your Birthday 6. Make A Picture  Side B: 7. Atomized 8. Faithless Ghost 9. Eight 10. Stop N' Shop 11. Never Fall Apart",
  'image': 'https://m.media-amazon.com/images/I/41KcVfXkRYL.jpg',
  'rating_number': 110,
  'price': 27.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B3JV82X4'},
 {'description': 'Common Courtesy Lemon & Milky Clear Limited yellow and milky clear colored vinyl LP pressing. Reissue. Common Courtesy is the fifth album from A Day to Re member and is reissued on both CD and double LP vinyl for the first time since 2016. The newly packaged vinyl includes updated cover art and pressed on lemon and clear color in color vinyl with diecut album packaging. Since it\'s initial release in 2013 Common Courtesy has gone on to amass over 500k in total consumption and includes some of the bands biggest hits including "Right Back At it Again" and "Sometimes You\'re the Hammer, Sometimes You\'re the Nail". Over the course of the past several years, each of A Day to Remember\'s releases have hit No. 1 on Billboard\'s Rock, Indie and/or Alternative Charts, they\'ve sold more than a million units, racked up over 400 million Spotify streams and 500 million YouTube views, garnered two gold-selling albums and singles (and one silver album in the UK) and sold out entire continental tours, amassing a global fan base whose members number in the millions.',
  'image': 'https://m.media-amazon.com/images/I/41x7eMdm5IL.jpg',
  'rating_number': 591,
  'price': 27.7,
  'average_rating': 4.8,
  'parent_asin': 'B0BG62V5J4'},
 {'description': "The Complete Albums Collection The box set contains all eleven studio albums, researched extensively from all the very best available master tapes. I worked with renowned mastering engineer Miles Showell at Abbey Road studios to have the albums remastered at half speed which achieves the best quality possible Alan Parsons Originally released in 2014 on CD, The Alan Parsons Project – The Complete Albums Collection is now being made available in a beautifully packaged deluxe vinyl 11LP box set and is limited to 1,500 copies worldwide. It includes the 11 original studio albums including The Sicilian Defence album that they originally recorded in 1979 and was previously unreleased until 2014 when it was included within The Complete Album Collection 11CD box set. - All albums half speed remastered at Abbey Road and cut from hi-res files transferred from the best available master tapes where analogue was originally used and from the original digital master tapes for all albums from 1983 onwards with everything approved by Alan Parsons. - Pressed on heavyweight 180gm vinyl, and beautifully replicated sleeves including original text and imagery. - Beautifully packaged in a 'cigarette type' hardback outer box with the outer design containing the words that Eric Woolfson felt best described The Alan Parsons Project. - Includes 60 page 12” x 12” hardback book containing full lyrics, brand new sleeve notes and essay from Miles Showell, Abbey Road Studios on the half speed remastering process. - Also includes giant A1 size poster The Alan Parsons Project was a progressive rock music entity comprised of engineer/ producer Alan Parsons and songwriter, musician and manager Eric Woolfson. They released 10 concept albums which focused on subject matter such as science fiction, supernatural, literary and sociological themes between 1976 – 1987 and have sold in excess of 55 million albums world-wide. Their focus was on very high-quality studio sound production and they recorded most of their work at Abbey Road Studios in London. They used a variety of different lead vocalists and musicians on every album but did employ some relatively consistent session players such as guitarist Ian Bairnson, arranger Andrew Powell, bassist and vocalist David Paton, drummer Stuart Elliott, and vocalists Lenny Zakatek and Chris Rainbow – choosing who they felt was the best for each song rather than being constrained to moulding the material for one specific artist.",
  'image': 'https://m.media-amazon.com/images/I/418+icJvMWL.jpg',
  'rating_number': 671,
  'price': 401.73,
  'average_rating': 4.8,
  'parent_asin': 'B0BL2S3FSL'},
 {'description': "Let’s Talk About Love Originally released on 18th November 1997, Let's Talk About Love is the fifth English-language studio album Céline, and it features some of the most iconic tracks of all times, such as My Heart Will Go On, also on the “Titanic” Soundtrack, and Tell Him, the fabulous duet with Barbra Streisand. Let's Talk About Love became one of the best-selling albums in history, with sales of over 31 million copies worldwide, and it also topped the record charts globally, including the US, Canada, UK, France, Australia and many more!",
  'image': 'https://m.media-amazon.com/images/I/41NDxrJuoEL.jpg',
  'rating_number': 1303,
  'price': 28.49,
  'average_rating': 4.7,
  'parent_asin': 'B0BFJFN2XK'},
 {'description': 'I\'m Wide Awake, It\'s Morning Vinyl LP pressing. "The first three are innocent in a way, because we didn\'t have an audience when we were making them," Oberst says. "But from Lifted on, I was definitely aware of an audience. Lifted was well-received right away, and then everything happened with Wide Awake and Digital Ash." Those two albums came out simultaneously. And their lead singles - "Take It Easy (Love Nothing)," from the austere, remote Digital Ash, and "Lua," from the warm, folky Wide Awake - debuted in the top two slots on the Billboard Hot 100. "First Day of My Life," also from Wide Awake, would later be voted the Number One love song of all time by NPR Music\'s reader\'s poll. Bright Eyes had officially broken through. It was a heady, exciting time, but also fraught and tense, both because of the band\'s careening new fame, and because of the state of the world. When Bright Eyes made their Tonight Show debut in 2006, they chose to perform none of their shiny new hits, instead delivering a searing, harrowing rendition of their caustic anti-Bush anthem, "When The President Talks To God." These days, Oberst is still amusing himself by messing with the extremes Bright Eyes baked into this era\'s releases, extremes that reflected the polar, with-us-or-against-us, fractious feel of the times. The reworked Digital Ash tracks, originally so clean and elegant, are, on the companion EP, full of "harmonica and mandolins - folky vibes," Oberst says. While the analogue sweetness of the Wide Awake songs have been put through a detached nihilism filter.',
  'image': 'https://m.media-amazon.com/images/I/41MYWKLU3CL.jpg',
  'rating_number': 434,
  'price': 24.98,
  'average_rating': 4.6,
  'parent_asin': 'B0B97ZQZBK'},
 {'description': "Second Skin New hard rock/metal group featuring guitarist Michael Sweet (Stryper), guitarist Joel Hoekstra (Whitesnake), bassist Marco Mendoza (ex-Journey, Whitesnake), drummer Tommy Aldridge (Whitesnake, Ozzy Osbourne), and vocalist Nathan James (Inglorious). Four musicians with impeccable rock/metal resumes and one up-and-coming vocalist with the vocal chords to hang with the big boys! Musically, this is HUGE '70s/80s sounding metal with modern production. Visceral, anthemic, and ready for sing-alongs.",
  'image': 'https://m.media-amazon.com/images/I/61NikPkjZtL.jpg',
  'rating_number': 354,
  'price': 12.33,
  'average_rating': 4.6,
  'parent_asin': 'B09TPT5BHK'},
 {'description': 'Cotton Mouth Man Product Description 2013 album from the world famous Blues harp legend. On Cotton Mouth Man, James teams up with high-profile guests to deliver the deepest, most exciting release of his long career. Guest artists Gregg Allman, Joe Bonamassa, Ruthie Foster, Warren Haynes, Delbert McClinton and Keb Mo pay tribute to one of the last Blues giants by joining him in a joyous collection of raucous boogies, sunny Country Blues and brash Chicago shuffles. Review "The greatest living blues harmonica player." --The New York Daily News"Among the greats of all time…. He blazes on harp with brilliant virtuosity." --Rolling Stone"James Cotton is an inimitable blues legend. His wailing harmonica blows them away. His improvisations on the blues are full of fun and good humor. The blues don t get much better." --San Francisco Examiner',
  'image': 'https://m.media-amazon.com/images/I/516Q9Ge-sNL.jpg',
  'rating_number': 143,
  'price': 17.49,
  'average_rating': 4.7,
  'parent_asin': 'B00BSWMIOK'},
 {'description': "Disconnected (2018 Remaster) (DELUXE EDITION) Norwegian prog act Airbag is set to release a remastered version of their fourth album via Karisma Records on ___. Disconnected, originally released in 2016, was the follow-up to the bands critically acclaimed 2013 release ‘The Greatest Show on Earth’. The album features six songs with a common theme running through them. From the opening track, ‘Killer’, to the thirteen-minute long title track, the listener is taken on a sonic journey of lush soundscapes and arrangements, underlined by soaring guitars and soulful vocals. As always, Airbag masters the art of creating a strong narrative listening-experience by closely tying together lyrical themes and music. Another central point to make note of with Disconnected, is how Airbag ventures even deeper into blending musical styles and sounds, which also greatly contributes to creating the unique listening experience that Airbag is, by now, well-known for. Disconnected is a reflection on the theme of alienation between the individual and society, what society expects from us as individuals, and our resultant failure to live up to those expectations. Each of the six compositions depicts the state of feeling on 'the outside’ and out of touch with oneself and those around us. 1. Killer 2. Broken 3. Slave 4. Sleepwalker 5. Disconnected 6. Returned",
  'image': 'https://m.media-amazon.com/images/I/11IIGCpPUFL.jpg',
  'rating_number': 165,
  'price': 29.99,
  'average_rating': 4.6,
  'parent_asin': 'B07FSRBW5X'},
 {'description': "SEVENTEEN 4th Album 'Face the Sun'[ep.3 Ray] SEVENTEEN is back with a brand-new release. Their 4th album, entitled `Face the Sun' will be available in five different versions: ep.1 Control, ep.2 Shadow, ep.3 Ray, ep.4 Path & ep.5 Pioneer. Each version will contain a CD, Photobook, Limited Edition Artist Logo Highlighter, Lyrics Book, Photocard (random 4 of 52), PET Card, Postcard (random 2 of 26), Limited Edition Poster (random 1 of 5) and Retail Exclusive Postcard (random 1 of 3). Box dimensions: 292 x 186 x 22 (mm).",
  'image': 'https://m.media-amazon.com/images/I/31MPDTMWoDL.jpg',
  'rating_number': 487,
  'price': 30.99,
  'average_rating': 4.6,
  'parent_asin': 'B09Y96C5S1'},
 {'description': "MERCY . What does John Cale have that the rest of us don’t—some gene that engenders infinite restlessness, a rapacious mind that is never satisfied? For nearly 60 years, or at least since he was a young Welshman who moved to New York and joined The Velvet Underground, Cale has been reinventing his music with dazzling and inspiring regularity. Once again, here is Cale, reimagining how his music is made, sounds, and even works. His engrossing 12-track MERCY—his first full album of new tunes in a decade—moves through true dark-night-of-the-soul electronic blues toward vulnerable love songs and hopeful considerations for the future with the help of some of music’s most curious young minds. 1. MERCY feat. Laurel Halo2. MARILYN MONROE'S LEGS (beauty elsewhere) feat. Actress3. NOISE OF YOU4. STORY OF BLOOD feat. Weyes Blood5. TIME STANDS STILL feat. Sylvan Esso6. MOONSTRUCK (Nico's Song)7. EVERLASTING DAYS feat. Animal Collective8. NIGHT CRAWLING9. NOT THE END OF THE WORLD10. THE LEGAL STATUS OF ICE feat. Fat White Family11. I KNOW YOU'RE HAPPY feat. Tei Shi12. OUT YOUR WINDOW",
  'image': 'https://m.media-amazon.com/images/I/41SWQYeDuxL.jpg',
  'rating_number': 100,
  'price': 14.19,
  'average_rating': 4.5,
  'parent_asin': 'B0BJP8ZBRT'},
 {'description': 'Close Messa\'s rising trajectory hits the stratosphere on their immense new album Close. Soaring up out of the Italian Doom Rock underground in 2014, Messa have been rapidly garnering a frenzied throng of devotees, in thrall to their monumental and broad-ranging sound craft. Releasing two widely celebrated cult records, the latest of which Feast For Water in 2018 was a critical breakthrough success, with Rolling Stone calling the album "captivating, wringing maximum drama out of it\'s savvy stylistic clash," Messa have had everyone on tenterhooks, waiting for what was next. Close draws us further into Messa\'s spellbinding textures and immersive dynamics. Described as "Stevie Nicks fronting Black Sabbath," singer Sara\'s colossal voice omnipotently carries the listener on an emotional rollercoaster ride where the sonic cauldron of Iommi guitars gives way to Arabian oudh and progressive solos in a masterful style-clash that well befits Messa\'s incendiary reputation. The hushed Fender Rhodes piano intro on opener "Suspended," picks up where Messa left off on their previous album but then collapses gloriously into Jazz guitar and widescreen impassioned crushing riffs, lighting our way for the odyssey ahead.',
  'image': 'https://m.media-amazon.com/images/I/41M7BKOhblL.jpg',
  'rating_number': 127,
  'price': nan,
  'average_rating': 4.8,
  'parent_asin': 'B09MCHK499'},
 {'description': 'SMITHEREENS SMITHEREENS marks Joji’s first full-length since Nectar in 2020. He delivers his characteristically melancholic yet powerful vocals on tracks like “Die For You,” a sober, morning-after remembrance of a former love. SIDE A of the album heralds a mature sonic direction for Joji through wistful and contemplative ballads accompanied by lush production that blooms within each song.SIDE B, largely produced by Joji himself, digs deeper into the lo-fi and off-kilter sounds that hark back to his experimental beginnings as an artist.',
  'image': 'https://m.media-amazon.com/images/I/31zjDN37YjL.jpg',
  'rating_number': 300,
  'price': 27.98,
  'average_rating': 4.7,
  'parent_asin': 'B0BJCJHBQF'},
 {'description': 'The Call Of The Void Los Angeles native Nita Strauss has become a force in music. After reaching mass acclaim with her first album, Controlled Chaos, she returns with her 2nd full-length on Sumerian Records, The Call Of The Void. Featuring the highly popular "Dead Inside," and "The Wolf You Feed," the album is a combination of melodic sounds and hard-hitting riffs that Strauss has become known for, proving time and time again that she has solidified her presence as one of rock\'s greatest. CD with fold-out poster.',
  'image': 'https://m.media-amazon.com/images/I/61XDRBcFXyL.jpg',
  'rating_number': 137,
  'price': 12.98,
  'average_rating': 4.6,
  'parent_asin': 'B0C55KSG91'},
 {'description': '72 Seasons Metallica’s 12th studio album, 72 Seasons , will arrive on April 14, 2023, on the band’s own Blackened Recordings. Produced by Greg Fidelman with Hetfield & Ulrich and clocking in at over 77 minutes, the 12-track album is the band’s first full-length collection of new material since 2016’s Hardwired…To Self-Destruct . Speaking on the concept of the album title, James said: “72 seasons. The first 18 years of our lives that form our true or false selves. The concept that we were told ‘who we are’ by our parents. A possible pigeonholing around what kind of personality we are. I think the most interesting part of this is the continued study of those core beliefs and how it affects our perception of the world today. Much of our adult experience is a reenactment or reaction to these childhood experiences. Prisoners of childhood or breaking free of those bondages we carry.”',
  'image': 'https://m.media-amazon.com/images/I/5168ssP-H6L.jpg',
  'rating_number': 4482,
  'price': 13.97,
  'average_rating': 4.7,
  'parent_asin': 'B0BNJQMG9K'},
 {'description': 'Divisive Everywhere you look these days, hyper tribalism has taken hold. Those in power continue to use fear and hate mongering to further empower themselves, continuing to try to turn us against one another. Pick a subject…any subject, and those who wield power will do all they can to make it a divisive issue, encouraging people to pick a side, insisting that their viewpoint is the only correct one. This record is a critique of this dangerous status quo we are living in. - Disturbed',
  'image': 'https://m.media-amazon.com/images/I/514h6WmJquL.jpg',
  'rating_number': 978,
  'price': 18.76,
  'average_rating': 4.8,
  'parent_asin': 'B0BG3F848Q'},
 {'description': "Teaser And The Firecat Yusuf/Cat Stevens' 1971 landmark album, Teaser and the Firecat. Remastered by the original producer Paul Samwell-Smith at Abbey Road Studios on 180-gram LP in a gatefold jacket.",
  'image': 'https://m.media-amazon.com/images/I/41owv1GYPkL.jpg',
  'rating_number': 165,
  'price': 29.4,
  'average_rating': 4.7,
  'parent_asin': 'B09M57YCR2'},
 {'description': 'Evenings At The Village Gate: John Coltrane With Eric Dolphy : In August of 1961, the John Coltrane Quintet played an engagement at the legendary Village Gate in Greenwich Village, New York. Eighty minutes of never-before-heard music from this group were recently discovered at the New York Public Library. In addition to some well-known Coltrane material ("Impressions"), there is a breathtaking feature for Dolphy\'s bass clarinet on "When Lights Are Low" and the only known non-studio recording of Coltrane\'s composition "Africa", from the Africa/Brass album.',
  'image': 'https://m.media-amazon.com/images/I/51V5HyisxHL.jpg',
  'rating_number': 164,
  'price': 39.98,
  'average_rating': 4.2,
  'parent_asin': 'B0C415TN7L'},

### define the embedding function

In [16]:
### define the embedding function minilm
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
def embed_text(text):
    return model.encode(text).tolist()
# Example usage
text = "This is an example sentence."
embedding = embed_text(text)
print(embedding)

c:\Users\Loq\Documents\CRAP\end to end aibootcamp\code\handsON\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4213.16it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[0.09812459349632263, 0.06781266629695892, 0.06252316385507584, 0.0950847640633583, 0.03664756938815117, -0.003984653856605291, 0.0074775186367332935, -0.013231487944722176, 0.06288367509841919, 0.022495532408356667, 0.07269581407308578, -0.03127426281571388, 0.04635513573884964, -0.012554490007460117, 0.047814738005399704, -0.004910328891128302, 0.04941995441913605, -0.06410927325487137, -0.09696577489376068, 0.03288881480693817, 0.054104436188936234, 0.03532859683036804, 0.0330505445599556, 0.014699398539960384, -0.03343060612678528, -0.025615902617573738, -0.05079213157296181, 0.07325458526611328, 0.11027402430772781, -0.02966185286641121, -0.06755709648132324, -0.03057153709232807, 0.039560288190841675, 0.04547598958015442, 0.015996240079402924, 0.03855039179325104, -0.010954095050692558, 0.08483570069074631, -0.04428712651133537, -0.006796381436288357, 0.009425639174878597, 5.066889207228087e-05, 0.0013035230804234743, -0.011969797313213348, 0.013645161874592304, -0.0841742679476738, -0.0001651400962145999, 0.005483757704496384, 0.025615094229578972, -0.03154531866312027, -0.10734473913908005, -0.04578776657581329, -0.09117491543292999, -0.002510553225874901, 0.01799841597676277, 0.049401577562093735, 0.006184803321957588, 0.0597962848842144, 0.027002615854144096, -0.016122275963425636, -0.01814970187842846, -0.02363485097885132, -0.09489715844392776, 0.06621628999710083, 0.1492275446653366, 0.024338804185390472, 0.0012102299369871616, 0.0060720741748809814, -0.09917043894529343, 0.08505815267562866, 0.030826125293970108, 0.02918659709393978, -0.02395590767264366, -0.010559311136603355, -0.07215199619531631, -0.03525640442967415, 0.03334658592939377, -0.043929487466812134, 0.11975514888763428, 0.08864741772413254, -0.09591908007860184, -0.05908011645078659, -0.008292684331536293, 0.03816917538642883, 0.04979968070983887, -0.032682135701179504, 0.01990094967186451, -0.10837846994400024, 0.014679083600640297, 0.01811780035495758, -0.06131787225604057, -0.08975031971931458, 0.04922166094183922, -0.020871026441454887, 0.004055106081068516, -0.035430166870355606, -0.056577738374471664, -0.04831375181674957, -0.024660343304276466, 0.07359187304973602, -0.02092357911169529, 0.04069768264889717, 0.032326485961675644, 0.07668343186378479, -0.01474765595048666, -0.10304528474807739, -0.04274498298764229, -0.0662931427359581, 0.015474033541977406, -0.026800287887454033, -0.09175191074609756, -0.0356004536151886, -0.018932482227683067, -0.004029614385217428, -0.020193416625261307, -0.058534830808639526, -0.10180169343948364, -0.004487866070121527, -0.06976299732923508, 0.0602409727871418, 0.0298108272254467, 0.06380829960107803, -0.06730611622333527, 0.0033509209752082825, -0.06003985553979874, -0.09313667565584183, 0.04567502811551094, -6.719925780142724e-33, 0.007433225866407156, -0.0651097223162651, -0.021259145811200142, 0.03519604727625847, 0.0463361032307148, -0.07030493021011353, -0.06128953769803047, 0.017366617918014526, -0.00747975567355752, -0.018468748778104782, 0.0016074704471975565, -0.025801822543144226, 0.030047012493014336, 0.008751633577048779, 0.05092955008149147, 0.07171621173620224, -0.07271795719861984, 0.13261514902114868, -0.00803411565721035, 0.03693223372101784, -0.02369135245680809, 0.024269407615065575, -0.026396233588457108, -0.018338482826948166, -0.01475323922932148, -0.0743173360824585, 0.01634487509727478, 0.018036991357803345, -0.003123264294117689, 0.04128267243504524, 0.05059867724776268, 0.04449483007192612, -0.04755299538373947, -0.002626463770866394, 0.05466777831315994, 0.04697798192501068, 0.06379823386669159, -0.021836763247847557, 0.0011920200195163488, 0.006154988892376423, -0.010474746115505695, -0.05154886096715927, 0.02171897515654564, -0.037872131913900375, 0.0879114642739296, 0.023657532408833504, 0.019885674118995667, 0.021743128076195717, -0.06192104518413544, 0.02061617188155651, -0.01068702433258295, 0.057762209326028824, 0.05940286070108414, -0.028875602409243584, 0.0694771409034729, 0.0010136277414858341, 0.042008016258478165, 0.034751977771520615, -0.0016648184973746538, -0.01012809295207262, -0.05472000688314438, 0.040564730763435364, -0.05601636320352554, 0.05726315453648567, -0.025761008262634277, 0.02939694933593273, 0.010298478417098522, -0.049152445048093796, 0.015427705831825733, 0.028693392872810364, 0.011681490577757359, -0.006968741770833731, -0.08346766978502274, 0.1083698570728302, -0.04198266938328743, -0.04266297444701195, -0.021897364407777786, -0.021625980734825134, -0.007852149195969105, 0.03822033852338791, -0.01800900138914585, -0.14943552017211914, 0.023226456716656685, 0.015028481371700764, -0.03989404812455177, 0.0037517407909035683, 0.04300670698285103, -0.084754578769207, -0.03029683232307434, -0.02013072557747364, -0.025030184537172318, 0.0035260221920907497, 0.058234792202711105, 0.005494760815054178, 0.0064897420816123486, 3.1746829398626915e-33, -0.04243820533156395, 0.02992222085595131, -0.08836190402507782, 0.06575310975313187, 0.10463085025548935, -0.00889668706804514, 0.042894504964351654, -0.09550553560256958, 0.03168182820081711, 0.07352752238512039, -0.13084881007671356, 0.025529934093356133, 0.0160621777176857, -0.004375639371573925, 0.029202545061707497, -0.00813413504511118, 0.06525740027427673, 0.0006216010078787804, -0.007835804484784603, 0.04156063124537468, -0.04372049495577812, 0.09504027664661407, -0.025842612609267235, 0.08701659739017487, -0.04147149249911308, 0.03544050082564354, -0.014387145638465881, -0.02607526071369648, -0.09590038657188416, -0.008881526067852974, 0.007069965358823538, -0.0905238538980484, -0.0797419399023056, -0.014227647334337234, -0.053489938378334045, 0.051225658506155014, 0.02454078570008278, -0.03697465360164642, -0.07341102510690689, -0.006874277256429195, 0.00681254593655467, -0.032918307930231094, 0.015790734440088272, 0.10594555735588074, 0.022715074941515923, -0.056417275220155716, -0.03206421807408333, -0.10509155690670013, -0.03290461376309395, 0.0513918399810791, -0.10034644603729248, 0.04499521851539612, -0.03296136111021042, -0.019640840590000153, -0.10540888458490372, 0.01197365764528513, -0.011170906946063042, -0.06957731395959854, -0.009789686650037766, 0.016010913997888565, -0.05117950588464737, 0.008791360072791576, -0.006576130632311106, 0.06629250943660736, 0.10956108570098877, -0.05475927144289017, -0.0570933073759079, 0.05029771104454994, 0.01262249331921339, 0.02845410443842411, 0.1343768984079361, 0.01101367175579071, -0.15195168554782867, -0.04947611317038536, -0.06537331640720367, -0.06709234416484833, -0.06969746947288513, -0.031295642256736755, -0.06176607310771942, -0.07420399785041809, 0.02897379919886589, -0.008312449790537357, 0.043219294399023056, -0.01755739003419876, -0.005178655032068491, -0.054324328899383545, -0.04127555340528488, -0.08270689845085144, -0.0159864854067564, 0.008618008345365524, 0.0006255587795749307, -0.06523493677377701, 0.07926347106695175, 0.026802241802215576, -0.025414058938622475, -1.965175400187036e-08, -0.022532736882567406, -0.015100579708814621, 0.08194086700677872, -0.039590414613485336, 0.047110848128795624, 0.015206322073936462, 0.06537680327892303, 0.018435344099998474, -0.007971729151904583, -0.03773096948862076, 0.023044059053063393, 0.040450286120176315, -0.05697205662727356, -0.0030700627248734236, 0.05366632714867592, 0.060949310660362244, 0.03831557556986809, -0.038075655698776245, -0.02675456367433071, 0.0674038752913475, -0.05417703837156296, 0.04589831456542015, -0.01290861051529646, 0.015068494714796543, 0.033009324222803116, 0.0049808151088654995, 0.043408624827861786, 0.06518961489200592, 0.016215670853853226, 0.03613709658384323, 0.05567418038845062, 0.11904111504554749, 0.02405668795108795, 0.015141707845032215, 0.060563813894987106, 0.03681965917348862, 0.04125630855560303, -0.031558919697999954, 0.05625439062714577, -0.02575591392815113, 0.013329334557056427, 0.04844074323773384, -0.021774696186184883, 0.11008106917142868, 0.038589540868997574, 0.03805918991565704, -0.004871056415140629, -0.04328329488635063, -0.025374168530106544, 0.01601370796561241, 0.018330948427319527, 0.05638065189123154, 0.03461504355072975, -0.020659934729337692, 0.021277641877532005, 0.018937913700938225, 0.03383444994688034, -0.006962493062019348, -0.024325978010892868, -0.01978025771677494, -0.019895371049642563, 0.034644052386283875, 0.049627237021923065, -0.029212981462478638]

In [17]:
len(embedding)

384

In [18]:
def get_embedding(text,model_name="all-MiniLM-L6-v2"):
    model = SentenceTransformer(model_name)
    return model.encode(text).tolist()

### create qdrant collections

In [20]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [21]:
qdrant_client.create_collection(
    collection_name="amazon-items-collection-00",
    vectors_config=VectorParams(size=384, distance=Distance.COSINE)
)

True

### Embed Data

#### Test

In [22]:
pointstruct=PointStruct(
    id=0,
    vector=get_embedding("Test Text"),
    payload={
        "text": "Test Text",
        "model": "all-MiniLM-L6-v2"
    },
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7955.17it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [23]:
pointstruct

PointStruct(id=0, vector=[0.0357932411134243, 0.08075187355279922, -0.022894641384482384, 0.03583967685699463, -0.01652579754590988, 0.02314174920320511, 0.06864471733570099, 0.013322337530553341, 0.018502315506339073, -0.012461098842322826, 0.07817526906728745, -0.012404758483171463, 0.03556797653436661, 0.007992545142769814, 0.03585612773895264, -0.0376138761639595, 0.04076767340302467, -0.017905496060848236, -0.03391685336828232, -0.05569085106253624, 0.02311631664633751, 0.04743529111146927, 0.017255960032343864, 0.04447336494922638, -0.01573190838098526, 0.10072934627532959, -0.08943486213684082, 0.02642359770834446, 0.026291079819202423, -0.021334869787096977, -0.021611902862787247, 0.03308769315481186, 0.07231839746236801, 0.07236592471599579, 0.057040996849536896, -0.003308030543848872, -0.03990710526704788, 0.03111330047249794, 0.017501384019851685, 0.03648112714290619, -0.06317993253469467, -0.11546606570482254, 0.0389338918030262, 0.02778879553079605, 0.09715817868709564, -0.03707768768072128, -0.05982108414173126, 0.03867047280073166, -0.010652877390384674, 0.011212358251214027, -0.041484858840703964, -0.04153243452310562, -0.01007565762847662, -0.035200461745262146, -0.026058794930577278, 0.06926442682743073, 0.05421175807714462, -0.034825827926397324, 0.04389336705207825, -0.0006410229834727943, -0.010064640082418919, -0.00731997936964035, 0.0020236442796885967, 0.020866792649030685, 0.030857691541314125, 0.028853313997387886, 0.007335635367780924, 0.018392259255051613, -0.08496623486280441, -0.023516904562711716, -0.037918198853731155, 0.03264384716749191, 0.04466133564710617, 0.13082976639270782, -0.007594702765345573, 0.021277695894241333, -0.05117194727063179, -0.09594576805830002, 0.061039987951517105, 0.004657434299588203, -0.06092632934451103, -0.07603196054697037, 0.04098076373338699, 0.10954868048429489, 0.03354015201330185, 0.10272940993309021, 0.08199399709701538, 0.04351866990327835, -0.06547895818948746, 0.014720178209245205, 0.04998687654733658, -0.056721191853284836, 0.01844068616628647, 0.02029164880514145, -0.10548609495162964, 0.06402591615915298, -0.030434969812631607, -0.06691141426563263, 0.012202015146613121, 0.15707916021347046, 0.025576608255505562, -0.014177006669342518, 0.02884354442358017, -0.023610299453139305, -0.1178538128733635, -0.027268491685390472, 0.11735645681619644, -0.12205379456281662, 0.07621277123689651, -0.0621628500521183, 0.0460941344499588, -0.03815465420484543, -0.06742635369300842, -0.034650690853595734, 0.0021931654773652554, -0.12202885001897812, -0.005831762682646513, -0.020399432629346848, -0.006858645938336849, 0.056458618491888046, 0.013080833479762077, -0.0008844519034028053, -0.0472860187292099, 0.011940019205212593, -0.0025022788904607296, 0.010836859233677387, 0.10147879272699356, -2.1716271818213025e-33, -0.021095911040902138, -0.02172980085015297, 0.022209148854017258, 0.11023826897144318, -0.030593831092119217, 0.021285302937030792, -0.06863705068826675, 0.03946339711546898, -0.029091808944940567, -0.010273918509483337, 0.03223256766796112, -0.04406045004725456, 0.01442014891654253, -0.013549215160310268, 0.01741129718720913, 0.009767260402441025, -0.018070176243782043, 0.0011340765049681067, -0.017460128292441368, -0.015961434692144394, -0.028364306315779686, -0.054871611297130585, 0.0378037728369236, -0.05400172621011734, -0.03782990574836731, -0.0008450720342807472, -0.013646846637129784, -0.03278041630983353, -0.0036534168757498264, -0.007096791639924049, -0.04539195075631142, -0.032470740377902985, -0.016728289425373077, 0.0581480972468853, 0.00854017399251461, 0.0395602285861969, 0.011303874664008617, -0.004136746283620596, -0.03177521005272865, 0.013274971395730972, -0.09547142684459686, -0.01369817741215229, 0.08014080673456192, -0.03240217640995979, 0.03855478763580322, 0.007298788987100124, -0.0672679916024208, -0.01404989417642355, 0.017365802079439163, -0.021351514384150505, -0.003368545090779662, 0.09315653145313263, -0.019810765981674194, -0.0196960661560297, 0.069085992872715, 0.04839211329817772, 0.017231537029147148, 0.00698100496083498, 0.0148461377248168, 0.06674706190824509, 0.0039571127854287624, 0.015588230453431606, 0.024735521525144577, 0.04184405878186226, -0.0044675651006400585, -0.01950065977871418, -0.0721234530210495, -0.13993211090564728, 0.07188612967729568, -0.006625133100897074, -0.012841791845858097, -0.08346050977706909, -0.042505893856287, 0.03181879222393036, -0.05280263349413872, -0.03476233780384064, -0.013532260432839394, 0.015461628325283527, -0.043883562088012695, -0.06499612331390381, 0.08221154659986496, -0.12352828681468964, 0.062030013650655746, -0.035669535398483276, -0.007560991682112217, -0.04014921933412552, 0.016208888962864876, -0.1573033183813095, 0.03277440741658211, -0.04455746337771416, -0.019146012142300606, 0.026073485612869263, -0.06105097755789757, -0.04550744220614433, 0.13437455892562866, 1.2086207918189173e-33, -0.011272605508565903, 0.040810924023389816, -0.04376845061779022, 0.08488913625478745, 0.0038588575553148985, 0.013586269691586494, 0.07971362769603729, 0.019790323451161385, -0.0008345438400283456, 0.022284328937530518, 0.033287711441516876, 0.02967078797519207, -0.03066904842853546, -0.034525394439697266, -0.026475898921489716, 0.023126835003495216, 0.015057472512125969, -0.0063938782550394535, 0.01905032806098461, 0.00848329532891512, -0.0803401991724968, 0.013188094832003117, -0.05032777413725853, -0.02065197378396988, -0.047380268573760986, 0.026627063751220703, 0.03495224937796593, -0.02636110410094261, -0.006874257232993841, -0.024400975555181503, 0.00374599639326334, 0.05094362795352936, -0.004995595198124647, 0.08986450731754303, -0.0041231862269341946, -0.03384184092283249, 0.11108367890119553, -0.04918024688959122, -0.016540180891752243, 0.06591834127902985, 0.12736158072948456, 0.07035671174526215, 0.0017361959908157587, -0.0178467258810997, -0.03646475076675415, 0.038206811994314194, -0.05644864961504936, -0.04976186528801918, 0.04903546720743179, 0.04337237402796745, 0.0029614800587296486, -0.04229122772812843, -0.012398209422826767, -0.030171474441885948, -0.03759565204381943, -0.029781442135572433, -0.06501980125904083, -0.017100617289543152, -0.06681814044713974, 0.013067660853266716, -0.08486565202474594, 0.05544105917215347, 0.02443634532392025, 0.06533730775117874, 0.03043433092534542, -0.11942736804485321, -0.0056251524947583675, 0.02965637482702732, -0.010649878531694412, -0.003769455011934042, 0.04180371016263962, -0.0279525313526392, -0.05656050145626068, -0.02990799769759178, 0.02493373677134514, 0.026353856548666954, -0.0341779850423336, -0.011512945406138897, -0.05757328122854233, -0.0168843362480402, 0.09276697784662247, 0.003386744763702154, -0.06001446396112442, 0.08639123290777206, -0.0031376201659440994, 0.0741971880197525, -0.026072794571518898, 0.035442277789115906, -0.03978068009018898, 0.01594194583594799, 0.010753225535154343, 0.062071315944194794, 0.008991178125143051, 0.021350761875510216, -0.02149360626935959, -1.2740916766063037e-08, -0.029986580833792686, -0.12239456176757812, -0.04653528705239296, 0.0069024330005049706, -0.07575107365846634, 0.03927309438586235, -0.008189169690012932, -0.0950353816151619, -0.047686394304037094, -0.05975194647908211, -0.006169949192553759, -0.006801709998399019, -0.04473799839615822, -0.021911876276135445, 0.013414273969829082, -0.015551511198282242, 0.010732568800449371, -0.020758163183927536, 0.01213967613875866, 0.014202742837369442, 0.04356905072927475, 0.08541008085012436, 0.006698764394968748, 0.05774752050638199, -0.06512092053890228, 0.0788552463054657, -0.03019632026553154, 0.058778587728738785, -0.012349912896752357, -0.019757648929953575, 0.13500995934009552, 0.028107397258281708, -0.04221038892865181, -0.06999441981315613, 0.03723440691828728, 0.04959462583065033, 0.05396683141589165, -0.001213784678839147, 0.0710122287273407, 0.06924062967300415, -0.009473777376115322, 0.0038724117912352085, -0.08030818402767181, -0.05485763028264046, 0.01830681785941124, -0.06254049390554428, -0.01913517341017723, -0.12205640226602554, 0.015292581170797348, -0.10171590745449066, -0.009422165341675282, -0.004186613950878382, -0.019259311258792877, 0.0031430877279490232, -0.030916906893253326, -0.03726283460855484, 0.09875719249248505, 0.05894409492611885, -0.08436894416809082, 0.03384540230035782, 0.1076878011226654, 0.0714598223567009, 0.05000083148479462, -0.05729923024773598], payload={'text': 'Test Text', 'model': 'all-MiniLM-L6-v2'})

### Amazon data

In [24]:
pointstructs=[]

for i,data in enumerate(data_to_embed):
    embedding=get_embedding(data["description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data
        )
    )

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7194.11it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8264.40it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5894.65it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7035.36it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4397.75it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3588.12it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4207.01it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3475.54it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3369.73it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3572.19it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3298.49it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3418.91it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3384.68it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3407.13it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3624.42it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3603.86it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3345.49it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3720.40it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4257.13it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3337.97it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3454.75it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3519.11it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3117.72it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3238.89it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3462.12it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3273.97it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3907.75it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3062.14it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3420.72it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3375.74it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3431.75it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3753.90it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3105.22it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3427.32it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2964.07it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3167.11it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3612.57it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3361.87it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3294.74it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3286.92it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3124.53it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3530.50it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3203.02it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3615.05it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3141.05it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3150.00it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3224.94it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3470.74it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3083.50it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2753.48it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [26]:
len(pointstructs)

50

### write embedded data to Qdrant

In [27]:
qdrant_client.upsert(
    collection_name="amazon-items-collection-00",
    wait=True,
    points=pointstructs
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

### def function for data retreval

In [30]:
def retrieve_data(query, top_k=5):
    query_embedding=get_embedding(query)
    search_result=qdrant_client.query_points(
        collection_name="amazon-items-collection-00",
        query=query_embedding,
        limit=top_k,
    )
    return search_result

### test retreive

In [31]:
## test retreive

retrieve_data("Which album has great sound quality and a unique blend of genres?", top_k=10).points

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7870.53it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[ScoredPoint(id=11, version=1, score=0.40321946, payload={'description': "MERCY . What does John Cale have that the rest of us don’t—some gene that engenders infinite restlessness, a rapacious mind that is never satisfied? For nearly 60 years, or at least since he was a young Welshman who moved to New York and joined The Velvet Underground, Cale has been reinventing his music with dazzling and inspiring regularity. Once again, here is Cale, reimagining how his music is made, sounds, and even works. His engrossing 12-track MERCY—his first full album of new tunes in a decade—moves through true dark-night-of-the-soul electronic blues toward vulnerable love songs and hopeful considerations for the future with the help of some of music’s most curious young minds. 1. MERCY feat. Laurel Halo2. MARILYN MONROE'S LEGS (beauty elsewhere) feat. Actress3. NOISE OF YOU4. STORY OF BLOOD feat. Weyes Blood5. TIME STANDS STILL feat. Sylvan Esso6. MOONSTRUCK (Nico's Song)7. EVERLASTING DAYS feat. Animal Collective8. NIGHT CRAWLING9. NOT THE END OF THE WORLD10. THE LEGAL STATUS OF ICE feat. Fat White Family11. I KNOW YOU'RE HAPPY feat. Tei Shi12. OUT YOUR WINDOW", 'image': 'https://m.media-amazon.com/images/I/41SWQYeDuxL.jpg', 'rating_number': 100, 'price': 14.19, 'average_rating': 4.5, 'parent_asin': 'B0BJP8ZBRT'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=0, version=1, score=0.38711154, payload={'description': "I Am The Moon: IV. Farewell The fifth studio project from the Tedeschi Trucks band is the most ambitious and, at the same time, intimate record that America's best rock n' roll big band has ever made: a genuinely epic undertaking in four episodes and 24 songs inspired by classical literature but emotionally driven by the immediate drama, isolation and mourning of the pandemic era. CD Softpak.", 'image': 'https://m.media-amazon.com/images/I/315JEh2Xh9L.jpg', 'rating_number': 309, 'price': 10.98, 'average_rating': 4.7, 'parent_asin': 'B09XVCWQGL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=44, version=1, score=0.37829483, payload={'description': "Now That's What I Call Punk & New Wave / Various Limited Pink Double vinyl LP pressing. NOW Music proudly presents NOW That's What I Call Punk & New Wave - a collection encapsulating the spirit of the times, and of the movement that changed the course of mainstream pop music. 34 tracks across 2 LPs, present the era's most iconic artists, including The Clash, Blondie, Ramones, U2, Siouxsie And The Banshees, Adam & The Ants, The Jam and The Cure. The late 70s and early 80s saw an explosion of punk and new wave groups and artists moving from the underground to mainstream chart success. No.1s from The Jam with 'Going Underground', 'Brass In Pocket' by Pretenders, The Boomtown Rats' 'Rat Trap', Dexys Midnight Runners' 'Geno', and Ian Dury & The Blockheads' 'Hit Me With Your Rhythm Stick' are all here, as well as top 5 hits from Squeeze, Tom Robinson Band and Patti Smith. The genre also gave the first crossover success for bands that became the biggest acts in music during the late 70s and early 80s, including The Police, U2, The Cure, Blondie, all featured - along with Adam & The Ants' 'Dog Eat Dog' from their breakthrough album 'Kings Of The Wild Frontier'. A fantastic collection of unique tracks that summarize an incredible time for music.", 'image': 'https://m.media-amazon.com/images/I/618YTymNscL.jpg', 'rating_number': 742, 'price': None, 'average_rating': 4.7, 'parent_asin': 'B09MVH85ZP'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=1, score=0.37448227, payload={'description': "Creatures Of The Night (40th Anniversary)[Super Deluxe 5 CD/Blu-ray Audio] The 40th Anniversary Super Deluxe box set boasts 103 total tracks (including 75 tracks previously unreleased). CD 1 contains the newly remastered album. CDs 2-3 feature 34 rarities. CDs 4-5 highlight 26 soundboard live recordings from the Creatures '82-'83 Tour and 7 rare tour sound effects. The Blu-ray Audio disc showcases a first-ever Atmos & 5.1 surround mix. An 80-page book includes extensive liner notes, rare posters, imagery and prints, a track-by-track newspaper and much more!", 'image': 'https://m.media-amazon.com/images/I/51yjeuEdpNL.jpg', 'rating_number': 432, 'price': 172.91, 'average_rating': 4.7, 'parent_asin': 'B0BCGJQ2FD'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=4, version=1, score=0.3446804, payload={'description': "The Complete Albums Collection The box set contains all eleven studio albums, researched extensively from all the very best available master tapes. I worked with renowned mastering engineer Miles Showell at Abbey Road studios to have the albums remastered at half speed which achieves the best quality possible Alan Parsons Originally released in 2014 on CD, The Alan Parsons Project – The Complete Albums Collection is now being made available in a beautifully packaged deluxe vinyl 11LP box set and is limited to 1,500 copies worldwide. It includes the 11 original studio albums including The Sicilian Defence album that they originally recorded in 1979 and was previously unreleased until 2014 when it was included within The Complete Album Collection 11CD box set. - All albums half speed remastered at Abbey Road and cut from hi-res files transferred from the best available master tapes where analogue was originally used and from the original digital master tapes for all albums from 1983 onwards with everything approved by Alan Parsons. - Pressed on heavyweight 180gm vinyl, and beautifully replicated sleeves including original text and imagery. - Beautifully packaged in a 'cigarette type' hardback outer box with the outer design containing the words that Eric Woolfson felt best described The Alan Parsons Project. - Includes 60 page 12” x 12” hardback book containing full lyrics, brand new sleeve notes and essay from Miles Showell, Abbey Road Studios on the half speed remastering process. - Also includes giant A1 size poster The Alan Parsons Project was a progressive rock music entity comprised of engineer/ producer Alan Parsons and songwriter, musician and manager Eric Woolfson. They released 10 concept albums which focused on subject matter such as science fiction, supernatural, literary and sociological themes between 1976 – 1987 and have sold in excess of 55 million albums world-wide. Their focus was on very high-quality studio sound production and they recorded most of their work at Abbey Road Studios in London. They used a variety of different lead vocalists and musicians on every album but did employ some relatively consistent session players such as guitarist Ian Bairnson, arranger Andrew Powell, bassist and vocalist David Paton, drummer Stuart Elliott, and vocalists Lenny Zakatek and Chris Rainbow – choosing who they felt was the best for each song rather than being constrained to moulding the material for one specific artist.", 'image': 'https://m.media-amazon.com/images/I/418+icJvMWL.jpg', 'rating_number': 671, 'price': 401.73, 'average_rating': 4.8, 'parent_asin': 'B0BL2S3FSL'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=37, version=1, score=0.3429623, payload={'description': "Things Happen That Way Throughout his six-decade long career, Dr. John embodied a near-mythic multitude of musical identities: Global Ambassador of New Orleans Funk, Jazz, and R&B, visionary bluesman, rock n' roll innovator, and a massively revered high priest of psychedelic voodoo. Things Happen That Way, his final studio album, adds another dimension to his musicality: a lifelong affinity for Country & Western. It's a glorious farewell from one of the most essential figures in music history. Softpak CD.", 'image': 'https://m.media-amazon.com/images/I/51fU6moqxzL.jpg', 'rating_number': 138, 'price': 12.99, 'average_rating': 4.7, 'parent_asin': 'B09Z6TY5F1'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=1, score=0.3410051, payload={'description': "Anything Is Possible Expanded Two CD set. Digitally remastered and expanded edition. Originally released November 1990 on Atlantic Records and included material co- written with Motown legend Lamont Dozier of the songwriting/production titans Holland-Dozier-Holland among it's 16 tracks. A special edition expanding the original 16 track release over two discs; Split evenly between dance (NRG UP Side) and ballads (Mood Swings), the album represented a period of artistic growth for Debbie and contains some of her best material, including the top 30 US hit 'Anything Is Possible', '(This So-Called) Miracle' and 'One Hand, One Heart'. Includes a whole disc of remixes by Masters At Work, PWL and Jellybean and non- album tracks 'The Most Beautiful Love Song' and 'So Close To Forever', a previously unreleased PWL remixes of 'One Step Ahead' and a 2022 introduction written by Debbie.", 'image': 'https://m.media-amazon.com/images/I/41yJOpVCxRL.jpg', 'rating_number': 117, 'price': 12.91, 'average_rating': 4.7, 'parent_asin': 'B09PVHGSRZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=41, version=1, score=0.33453858, payload={'description': "ATUM The Smashing Pumpkins have announced their highly anticipated twelfth studio album; a three-act rock opera album titled ATUM (pronounced Autumn). ATUM will feature 33-tracks, and is the sequel to 1995’s Mellon Collie and the Infinite Sadness and 2000’s Machina/Machine of God. ATUM was written and produced by Billy Corgan over the past 4 years. ATUM is a rock opera presented in three acts by inimitable American rock band The Smashing Pumpkins. The album tells an epic interplanetary story set in the not-too-distant future, though the songs themselves respectively stand on their own in the Pumpkins pantheon. This is the final installment in a concept album trilogy, which began with 1995’s Melancholy and the Infinite Sadness and then continued with 2000's Machina/The Machines of God. The album features three original members of the band—William Corgan, James Iha, and Jimmy Chamberlin—as well as longtime guitarist Jeff Schroeder. Corgan had been developing the idea for the rock opera for years, and the pandemic gave him the time off the road to meticulously complete it in the grandiose way he had intended. When The Smashing Pumpkins first emerged out of Chicago in 1988, the world had never heard a band quite like them. They spun together rock, pop, shoe-gaze, metal, goth, psychedelia, and electronic into a kaleidoscope of saccharine melodies, fuzzy distortion, bombastic orchestration, incendiary fretwork, eloquent songcraft, and unshakable hooks. Upon their formation, their sound was different, iconoclastic, and wholly new—and it still is today. As a result, they’ve sold over 30 million albums worldwide and collected two GRAMMY® Awards, two MTV VMAs, and an American Music Award. Their catalog is highlighted by the platinum Gish [1991], the quadruple-platinum Siamese Dream [1993], diamond-certified Mellon Collie and the Infinite Sadness [1995], platinum Adore [1998], and gold Machina/The Machines of God [2000]. In 2018, they embarked on one of their most successful tours ever, the Shiny and Oh So Bright Tour, followed by SHINY AND OH SO BRIGHT, VOL. 1 / LP: NO PAST. NO FUTURE. NO SUN. Meanwhile, 2020 saw the release of the band’s eleventh full-length and latest double album, CYR.", 'image': 'https://m.media-amazon.com/images/I/41hnDu8Gs3L.jpg', 'rating_number': 279, 'price': 55.12, 'average_rating': 4.4, 'parent_asin': 'B0BFXBY64H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=40, version=1, score=0.33330107, payload={'description': 'Night NIGHT is the new album from acclaimed pianist George Winston, and is his 16th solo piano album. As one of the foremost instrumental composers of our time, NIGHT is a vivid look into Winston’s nocturnal world where life begins as the sun sets on each day. NIGHT features four original Winston compositions, as well as stunning renditions of Leonard Cohen’s “Hallelujah” and Allen Toussaint’s “Freedom For The Stallion,” plus additional standout interpretations. Two decades in the making, NIGHT turns darkness into a prism of beauty as Winston captures his quintessential performances for a full-length studio album well worth the wait. George Winston has inspired fans and musicians alike with his singular solo acoustic piano songs selling more than 15 million albums. Winston’s music is evocative, offering us all a chance to take a step back from our perpetually busy lives and let our minds adventurously wonder. NIGHT is where things truly come alive for Winston.', 'image': 'https://m.media-amazon.com/images/I/41m3pud9x+L.jpg', 'rating_number': 136, 'price': 13.98, 'average_rating': 4.5, 'parent_asin': 'B09SJ3BCLJ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=2, version=1, score=0.32994044, payload={'description': "Andrew Bird Inside Problems (Indie Exclusive, Col Exclusive Apple Red Vinyl LP edition of Inside Problems.  Side A 1. Underlands 2. Lone Didion 3. Fixed Positions 4. Inside Problems 5. The Night Before Your Birthday 6. Make A Picture  Side B: 7. Atomized 8. Faithless Ghost 9. Eight 10. Stop N' Shop 11. Never Fall Apart", 'image': 'https://m.media-amazon.com/images/I/41KcVfXkRYL.jpg', 'rating_number': 110, 'price': 27.99, 'average_rating': 4.6, 'parent_asin': 'B0B3JV82X4'}, vector=None, shard_key=None, order_value=None)]